### ISSUE TITLE
[Crash] Crash when changing spaces to tabs

### ISSUE THREAD

**Issue by KwiatekMiki** [NotroDev/SkEditorPlus#52]
![image](https://user-images.githubusercontent.com/79092746/227613983-655ee3a4-5e07-4e41-9861-811398d24f16.png)
![image](https://user-images.githubusercontent.com/79092746/227613964-129778b1-eb36-427f-bca0-d67654eed0de.png)
![image](https://user-images.githubusercontent.com/79092746/227614020-0307a061-ada6-4f53-8508-161110669786.png)
![image](https://user-images.githubusercontent.com/79092746/227613853-9519924d-e466-4cf2-9c7b-a47040238551.png)
![image](https://user-images.githubusercontent.com/79092746/227614120-b4833ca6-f117-44df-86ac-8133c43b79f7.png)

```
   at AvalonEditB.Document.TextDocument.ThrowIfRangeInvalid(Int32 offset, Int32 length)
   at AvalonEditB.Document.TextDocument.Replace(Int32 offset, Int32 length, ITextSource text, OffsetChangeMap offsetChangeMap)
   at AvalonEditB.Document.TextDocument.Replace(Int32 offset, Int32 length, ITextSource text)
   at AvalonEditB.Document.TextDocument.Remove(Int32 offset, Int32 length)
   at SkEditorPlus.Windows.FormattingWindow.SpacesToTabs() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 97
   at SkEditorPlus.Windows.FormattingWindow.FormatClick(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 40
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at SkEditorPlus.Managers.FileManager.FormatCode() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Managers\FileManager.cs:line 426
   at SkEditorPlus.Functionalities.MenuBarFunc.Edit_MenuItem_Click(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Functionalities\MenuBarFunc.cs:line 147
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SkEditorPlus.App.Main()
```

**Comment by NotroDev** [comment]
hey, I'm aware of this bug. I was planning to remake this quick edit, but I'm sick right now and I'm not doing any progress.

**Comment by KwiatekMiki** [comment]
> hey, I'm aware of this bug. I was planning to remake this quick edit, but I'm sick right now and I'm not doing any progress.

ok, just CHANGE TWO LINES OF CODE!!!!
```
   at SkEditorPlus.Windows.FormattingWindow.SpacesToTabs() in **C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 97**
   at SkEditorPlus.Windows.FormattingWindow.FormatClick(Object sender, RoutedEventArgs e) in **C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Windows\FormattingWindow.xaml.cs:line 40**
```
