### ISSUE TITLE
PLease bro i wannet too chill Dev stream xD

### ISSUE THREAD

**Issue by Satanaelcode** [NotroDev/SkEditorPlus#74]
Could not load type 'SkEditorPlus.Managers.FileManager' from assembly 'SkEditorPlus, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null'.
   at CompletionUnlocker.Addon.OnTabChanged()
   at SkEditorPlus.Utilities.Controllers.TabController.<>c.<OnTabChanged>b__0_0(ISkEditorPlusAddon a) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Utilities\Controllers\TabController.cs:line 34
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SkEditorPlus.Utilities.Controllers.TabController.OnTabChanged() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Utilities\Controllers\TabController.cs:line 34
   at SkEditorPlus.Functionalities.TabControlFunc.OnTabChanged(Object sender, SelectionChangedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Functionalities\TabControlFunc.cs:line 21
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.TabControl.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at HandyControl.Controls.TabControl.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at MS.Internal.Controls.InnerItemCollectionView.Add(Object item)
   at System.Windows.Controls.ItemCollection.Add(Object newItem)
   at SkEditorPlus.Utilities.Builders.FileBuilder.Build(String header, String tooltip) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Utilities\Builders\FileBuilder.cs:line 55
   at SkEditorPlus.Utilities.FileManager.NewFile() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\Utilities\FileManager.cs:line 57
   at SkEditorPlus.MainWindow.<>c__DisplayClass12_0.<MainWindow_Loaded>b__7() in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\MainWindow.xaml.cs:line 255
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at SkEditorPlus.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in C:\Users\Notro\Desktop\Projekty\SkEditorPlus\SkEditorPlus\MainWindow.xaml.cs:line 253
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SkEditorPlus.App.Main()

**Comment by NotroDev** [comment]
Oh, I'm sorry.

I didn't update the addons and the new update broke them.

**Comment by NotroDev** [comment]
Please update the CompletionUnlocker addon to v1.0.2 and try again
